### ISSUE TITLE
'Cannot access 'createDefaultConfigFile' before initialization'

### ISSUE THREAD

**Issue by lopww** [Tenclea/YANG#141]
Hi,

```
USER@USER:~$ node '/home/USER/Desktop/YANG-main/app.js' 
/home/USER/Desktop/YANG-main/utils/logger.js:7
if (!existsSync('./config.yml')) createDefaultConfigFile();
                                 ^

ReferenceError: Cannot access 'createDefaultConfigFile' before initialization
    at Object.<anonymous> (/home/USER/Desktop/YANG-main/utils/logger.js:7:34)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/USER/Desktop/YANG-main/app.js:3:11)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)

Node.js v20.5.1
USER@USER:~$ 
```

Ubuntu 22.04.2 LTS
Node.js 20.5.1
NPM 9.8.0
├── app@0.1.0
├── bootstrap@5.3.1
├── chalk@4.1.2
├── cjs@0.0.11
├── express@4.18.2
├── js-yaml@4.1.0
├── logger@0.0.1
├── optimist@0.5.2
└── winston@3.10.0

**Comment by Tenclea** [comment]
Fixed in [v3.3.2](https://github.com/Tenclea/YANG/releases/tag/v3.3.2). Thank you for the detailled report :)
