### ISSUE TITLE
'TypeError: ProxyAgent is not a constructor'

### ISSUE THREAD

**Issue by lopww** [Tenclea/YANG#143]
Hi,

```
USER@USER:~$ sudo node '/home/USER/Desktop/YANG-main/app.js'

__   __ __  __  _  __
\ `v' //  \|  \| |/ _]
 `. .'| /\ | | ' | [/\
  !_! |_||_|_|\__|\__/
  v3.3.2 - by Tenclea

11:34:06 [INFO] » Downloading fresh proxies...
11:34:12 [INFO] » Downloaded 1000 proxies.
11:34:12 [INFO] » Checking 1000 proxies... This might take up to 7 minutes.
TypeError: ProxyAgent is not a constructor
    at checkProxy (/home/USER/Desktop/YANG-main/utils/proxy-checker.js:17:18)
    at proxies (/home/USER/Desktop/YANG-main/utils/proxy-checker.js:49:4)
    at new Promise (<anonymous>)
    at module.exports (/home/USER/Desktop/YANG-main/utils/proxy-checker.js:15:18)
    at /home/USER/Desktop/YANG-main/app.js:59:85
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Ubuntu 22.04.2 LTS
Node.js 20.5.1
NPM 9.8.0
├── app@0.1.0
├── bootstrap@5.3.1
├── chalk@4.1.2
├── cjs@0.0.11
├── express@4.18.2
├── https-proxy-agent@7.0.1
├── js-yaml@4.1.0
├── logger@0.0.1
├── needle@3.2.0
├── optimist@0.5.2
├── proxy-agent@6.3.0
└── winston@3.10.0

No change after 20 minutes and no difference in debug mode (or debug mode doesn't work :p)

Thanks.

**Comment by Tenclea** [comment]
You seem to have installed the wrong dependecies versions, especially the `proxy-agent` dependecy.
Please install `proxy-agent@5` and let me know if your issue is fixed

**Comment by lopww** [comment]
Yup that fixed it! But theres another error now with the needle module.

```
__   __ __  __  _  __
\ `v' //  \|  \| |/ _]
 `. .'| /\ | | ' | [/\
  !_! |_||_|_|\__|\__/
  v3.3.2 - by Tenclea

15:33:22 [INFO] » Downloading fresh proxies...
15:33:28 [INFO] » Downloaded 1000 proxies.
15:33:28 [INFO] » Checking 1000 proxies... This might take up to 7 minutes.
TypeError: Cannot set properties of undefined (setting 'rejectUnauthorized')
    at /home/USER/node_modules/needle/lib/needle.js:212:45
    at Array.forEach (<anonymous>)
    at Needle.setup (/home/USER/node_modules/needle/lib/needle.js:209:26)
    at Needle.start (/home/USER/node_modules/needle/lib/needle.js:302:57)
    at module.exports.<computed> [as get] (/home/USER/node_modules/needle/lib/needle.js:819:61)
    at checkProxy (/home/USER/Desktop/YANG-main/utils/proxy-checker.js:18:11)
    at proxies (/home/USER/Desktop/YANG-main/utils/proxy-checker.js:49:4)
    at new Promise (<anonymous>)
    at module.exports (/home/USER/Desktop/YANG-main/utils/proxy-checker.js:15:18)
    at /home/USER/Desktop/YANG-main/app.js:59:85
```

**Comment by lopww** [comment]
Oh nevermind, I fixed that by downgrading to needle@2

**Comment by Tenclea** [comment]
All good then, have a nice day :)
