### ISSUE TITLE
showing errors

### ISSUE THREAD

**Issue by KunalSingh19** [Tenclea/YANG#38]
/home/ks/YANG/app.js:79
                                if (!body?.message && !body?.subscription_plan) {
                                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Tenclea** [comment]
Your nodejs version is not supported, make sure to update to the latest one.
