### ISSUE TITLE
err

### ISSUE THREAD

**Issue by discordgladiator2** [Tenclea/YANG#50]
 node app.js
/home/runner/YANG/app.js:87
                if (!body?.message && !body?.subscription_plan) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
exit status 1

**Comment by Tenclea** [comment]
Hi, you need to upgrade to Node.js v16 or sooner.
